/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ProjectsProjectIdAnalyticsRouteImport } from './routes/projects.$projectId.analytics'
import { Route as ProjectsProjectIdBoardRouteImport } from './routes/projects.$projectId.board'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects.$projectId.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdAnalyticsRoute =
  ProjectsProjectIdAnalyticsRouteImport.update({
    id: '/projects/$projectId/analytics',
    path: '/projects/$projectId/analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdBoardRoute = ProjectsProjectIdBoardRouteImport.update({
  id: '/projects/$projectId/board',
  path: '/projects/$projectId/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/projects/$projectId/settings',
    path: '/projects/$projectId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/projects/$projectId/analytics': typeof ProjectsProjectIdAnalyticsRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/projects': typeof ProjectsIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/projects/$projectId/analytics': typeof ProjectsProjectIdAnalyticsRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/projects/$projectId/analytics': typeof ProjectsProjectIdAnalyticsRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/billing'
    | '/dashboard'
    | '/projects/'
    | '/api/public/stripe-webhook'
    | '/projects/$projectId/analytics'
    | '/projects/$projectId/board'
    | '/projects/$projectId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/billing'
    | '/dashboard'
    | '/projects'
    | '/api/public/stripe-webhook'
    | '/projects/$projectId/analytics'
    | '/projects/$projectId/board'
    | '/projects/$projectId/settings'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/billing'
    | '/dashboard'
    | '/projects/'
    | '/api/public/stripe-webhook'
    | '/projects/$projectId/analytics'
    | '/projects/$projectId/board'
    | '/projects/$projectId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  DashboardRoute: typeof DashboardRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ProjectsProjectIdAnalyticsRoute: typeof ProjectsProjectIdAnalyticsRoute
  ProjectsProjectIdBoardRoute: typeof ProjectsProjectIdBoardRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/analytics': {
      id: '/projects/$projectId/analytics'
      path: '/projects/$projectId/analytics'
      fullPath: '/projects/$projectId/analytics'
      preLoaderRoute: typeof ProjectsProjectIdAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/board': {
      id: '/projects/$projectId/board'
      path: '/projects/$projectId/board'
      fullPath: '/projects/$projectId/board'
      preLoaderRoute: typeof ProjectsProjectIdBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  DashboardRoute: DashboardRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ProjectsProjectIdAnalyticsRoute: ProjectsProjectIdAnalyticsRoute,
  ProjectsProjectIdBoardRoute: ProjectsProjectIdBoardRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
