REVOKE EXECUTE ON FUNCTION public.is_project_member(UUID,UUID) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.project_role_of(UUID,UUID) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.can_manage_project(UUID,UUID) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.can_edit_project(UUID,UUID) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.shares_project_with(UUID,UUID) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM anon, authenticated, public;
GRANT EXECUTE ON FUNCTION public.is_project_member(UUID,UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.project_role_of(UUID,UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_manage_project(UUID,UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_edit_project(UUID,UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.shares_project_with(UUID,UUID) TO authenticated;